# Generated by Django 6.0.1 on 2026-01-18 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('balance_date', models.DateTimeField(null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='transactions.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('date_posted', models.DateField()),
                ('description', models.TextField()),
                ('is_pending', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.account')),
            ],
        ),
    ]
