# Generated by Django 6.0.1 on 2026-01-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_bankconnection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_posted']},
        ),
    ]
