# Generated by Django 5.2.10 on 2026-02-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='icon',
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
