# Generated by Django 6.0.1 on 2026-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
