# Generated by Django 5.2.10 on 2026-01-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_category_transaction_icon_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='help-circle', max_length=50),
        ),
    ]
