# Generated by Django 5.2.10 on 2026-01-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
